[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

lib_deps =
  bblanchon/ArduinoJson@7.2.2
  fastled/FastLED@3.10.3

build_flags =
  -D FASTLED_INTERNAL=1
